version: '3.8'
# But my docker-compose version is 2.17.3

# volumes:
  # mariadb:
  # wordpress:

services:
  nginx-serv:
    build:
      context: ./requirements/nginx  # Path to your Dockerfile and nginx.conf
      dockerfile: Dockerfile
    image: nginx-img:test
    container_name: nginx-cont
    ports:
      - "443:443"
    restart: always
    #networks:
    #depends on:
    #volumes:

# Networks:
