version: '3.8'

volumes:
  mariadb-data:
    name: mariadb:data
  wordpress-data:
    name: wordpress:data

networks:
  mynetwork:
    name: mynetwork

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx-img
    container_name: nginx-cont
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - mynetwork
    restart: always
    volumes:
      - wordpress-data:/var/www/html

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress-img
    container_name: wordpress-cont
    ports:
      - "9000:9000"
    env_file: .env
    networks:
      - mynetwork
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress-data:/var/www/html

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb-img
    container_name: mariadb-cont
    ports:
      - "3306:3306"
    env_file: .env
    restart: always
    networks:
      - mynetwork
    volumes:
      - mariadb-data:/var/lib/mysql
      