USE mysql;
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PWD}';
CREATE DATABASE '${WORDPRESS_DB_NAME}' CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER '${WORDPRESS_DB_USER}'@'%' IDENTIFIED by '${WORDPRESS_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${WP_DATABASE_NAME}.* TO '${WORDPRESS_DB_USER}'@'%';
FLUSH PRIVILEGES;
